In [24]:
# Dependencies
import pandas as pd

In [25]:
# Store filepath in a variable
Gun_MS_2019 = "Resource/MASS_SHOOTINGS_IN_2019.csv"
Gun_MS_2020 = "Resource/MASS_SHOOTINGS_IN_2020.csv"
Gun_MS_2021 = "Resource/MASS_SHOOTINGS_IN_2021.csv"
Statelatlon="Resource/US_City_latLon.csv"

In [26]:
file_one_df = pd.read_csv(Gun_MS_2019)
file_two_df = pd.read_csv(Gun_MS_2020)
file_three_df = pd.read_csv(Gun_MS_2021)
LatLon_df=pd.read_csv(Statelatlon)

In [27]:
columnsplit=file_one_df['Incident Date'].str.split(",", expand=True)
file_one_df=file_one_df.assign(Date=columnsplit[0],Year=columnsplit[1])
file_one_df_1=file_one_df.drop(columns=["Incident Date","Operations"])
file_one_df_1.head()

,Incident ID,State,City Or County,Address,# Killed,# Injured,Date,Year
0,1582816,Illinois,Danville,1803 block of Westview Ave,0,5,December 29,2019
1,1582197,New York,Buffalo,50 block of Henrietta Ave,1,3,December 29,2019
2,1583444,California,Ceres,800 block of Allacante Dr,0,5,December 29,2019
3,1581590,California,Modesto,1900 block of Vernon Ave,1,3,December 27,2019
4,1581103,Texas,Houston,500 block of Smart St,2,7,December 27,2019

In [28]:
columnsplit_2=file_two_df['Incident Date'].str.split(",", expand=True)
file_two_df=file_two_df.assign(Date=columnsplit_2[0],Year=columnsplit_2[1])
file_two_df_2=file_two_df.drop(columns=["Incident Date", "Operations"])
file_two_df_2.head()

,Incident ID,State,City Or County,Address,# Killed,# Injured,Date,Year
0,1891461,Indiana,Indianapolis,8215 Center Run Road,1,3,December 31,2020
1,1890946,Oregon,Happy Valley,9200 block of SE Idleman Rd,0,4,December 31,2020
2,1886974,Illinois,Rockford,4007 E State St,3,3,December 26,2020
3,1886913,Florida,Tampa,N 20th St and E 7th Ave,2,2,December 26,2020
4,1887059,Massachusetts,Lynn,Washington St and Quincy Ter,1,5,December 26,2020

In [29]:
columnsplit_3=file_three_df['Incident Date'].str.split(",", expand=True)
file_three_df=file_three_df.assign(Date=columnsplit_3[0],Year=columnsplit_3[1])
file_three_df_3=file_three_df.drop(columns=["Incident Date", "Operations"])
file_three_df_3.head()

,Incident ID,State,City Or County,Address,# Killed,# Injured,Date,Year
0,2125227,California,Riverside,6000 Block of Mariposa Ave,0,6,September 25,2021
1,2124396,South Carolina,Aiken,749 Silver Bluff Rd,4,1,September 24,2021
2,2124887,California,Los Angeles,11600 block of Willowbrook Ave,0,4,September 24,2021
3,2123301,Pennsylvania,Philadelphia,38th St and Aspen St,0,4,September 23,2021
4,2123395,Tennessee,Collierville,240 New Byhalia Rd,2,14,September 23,2021

In [30]:
# LatLon
LatLon_df.head()

              Place Name   Latitude  Longitude
0        Oneida, NY, USA  43.095654 -75.669487
1  New Rochelle, NY, USA  40.922794 -73.791809
2  Mount Vernon, NY, USA  40.916695 -73.836815
3    Middletown, NY, USA  41.450123 -74.429253
4      Lockport, NY, USA  43.170048 -78.710464

In [31]:
columnsplit_4=LatLon_df['Place Name'].str.split(",", expand=True)
LatLon_df=LatLon_df.assign(City=columnsplit_4[0],County=columnsplit_4[1])
LatLon_df=LatLon_df.drop(columns=["County", "Place Name"])
LatLon_df.head()

    Latitude  Longitude          City
0  43.095654 -75.669487        Oneida
1  40.922794 -73.791809  New Rochelle
2  40.916695 -73.836815  Mount Vernon
3  41.450123 -74.429253    Middletown
4  43.170048 -78.710464      Lockport

In [32]:
Gun_map_2019=file_one_df_1.merge(LatLon_df, left_on='City Or County', right_on='City')
Gun_map_2020=file_two_df_2.merge(LatLon_df, left_on='City Or County', right_on='City')
Gun_map_2021=file_three_df_3.merge(LatLon_df, left_on='City Or County', right_on='City')
Gun_map_2019.head(50)

,Incident ID,State,City Or County,Address,# Killed,# Injured,Date,Year,Latitude,Longitude,City
0,1582197,New York,Buffalo,50 block of Henrietta Ave,1,3,December 29,2019,42.880230,-78.878738,Buffalo
1,1418548,New York,Buffalo,2081 Niagara St,0,4,June 9,2019,42.880230,-78.878738,Buffalo
2,1581590,California,Modesto,1900 block of Vernon Ave,1,3,December 27,2019,37.661388,-120.994446,Modesto
3,1581103,Texas,Houston,500 block of Smart St,2,7,December 27,2019,29.749907,-95.358421,Houston
4,1541774,Texas,Houston,5000 block of Northridge Dr,1,4,November 4,2019,29.749907,-95.358421,Houston
5,1486232,Texas,Houston,4900 block of Southwind St,3,2,August 23,2019,29.749907,-95.358421,Houston
6,1481989,Texas,Houston,12500 block of Mylla St,0,6,August 17,2019,29.749907,-95.358421,Houston
7,1445066,Texas,Houston,5901 Royal Palms St,0,4,July 11,2019,29.749907,-95.358421,Houston
8,1332429,Texas,Houston,12800 block of Eastbrook Dr,2,2,February 21,2019,29.749907,-95.358421,Houston
9,1314289,Texas,Houston,7815 Harding St,2,5,January 28,2019,29.749907,-95.358421,Houston
10,1305294,Texas,Houston,7041 Sherman St,3,2,January 19,2019,29.749907,-95.358421,Houston
11,1579889,California,Oakland,2100 block of 34th Ave,0,4,December 25,2019,37.804363,-122.271111,Oakland
12,1504012,California,Oakland,38th Ave and MacArthur Blvd,1,4,September 14,2019,37.804363,-122.271111,Oakland
13,1435804,California,Oakland,3000 block of Brookdale Ave,0,4,June 30,2019,37.804363,-122.271111,Oakland
14,1338860,California,Oakland,316 14th St,0,4,March 3,2019,37.804363,-122.271111,Oakland
15,1337498,California,Oakland,9755 Edes Ave,1,3,February 28,2019,37.804363,-122.271111,Oakland
16,1579856,Virginia,Richmond,1800 E Main St,1,3,December 25,2019,37.541290,-77.434769,Richmond
17,1579856,Virginia,Richmond,1800 E Main St,1,3,December 25,2019,37.935757,-122.347748,Richmond
18,1554446,California,Richmond,20th St and Roosevelt Ave,0,4,November 20,2019,37.541290,-77.434769,Richmond
19,1554446,California,Richmond,20th St and Roosevelt Ave,0,4,November 20,2019,37.935757,-122.347748,Richmond
20,1475361,Virginia,Richmond,6346 Midlothian Turnpike,0,4,August 10,2019,37.541290,-77.434769,Richmond
21,1475361,Virginia,Richmond,6346 Midlothian Turnpike,0,4,August 10,2019,37.935757,-122.347748,Richmond
22,1428229,California,Richmond,700 block of 14th St,0,5,June 21,2019,37.541290,-77.434769,Richmond
23,1428229,California,Richmond,700 block of 14th St,0,5,June 21,2019,37.935757,-122.347748,Richmond
24,1579266,Louisiana,New Orleans,6400 block of General Meyer Ave,0,4,December 24,2019,29.951065,-90.071533,New Orleans
25,1567231,Louisiana,New Orleans,3801 Washington Ave,1,4,December 8,2019,29.951065,-90.071533,New Orleans
26,1561966,Louisiana,New Orleans,2000 block of N Dorgenois St,2,2,December 1,2019,29.951065,-90.071533,New Orleans
27,1561734,Louisiana,New Orleans,700 block of Canal St,0,12,December 1,2019,29.951065,-90.071533,New Orleans
28,1509411,Louisiana,New Orleans,Poland Ave and St. Claude Ave,0,4,September 21,2019,29.951065,-90.071533,New Orleans
29,1508859,Louisiana,New Orleans,Canal Blvd and City Park Ave,1,5,September 20,2019,29.951065,-90.071533,New Orleans
30,1393960,Louisiana,New Orleans,2100 block of 4th St,0,4,May 13,2019,29.951065,-90.071533,New Orleans
31,1329075,Louisiana,New Orleans,Tulane Ave and Elk Pl,1,5,February 17,2019,29.951065,-90.071533,New Orleans
32,1594317,Illinois,Joliet,1200 block of Cutter Ave,0,5,December 24,2019,41.520557,-88.150558,Joliet
33,1579220,North Carolina,High Point,1226 Montlieu Ave,0,6,December 24,2019,35.970554,-79.997498,High Point
34,1577577,Maryland,Baltimore,225 Park Ave,0,7,December 22,2019,39.299236,-76.609383,Baltimore
35,1537044,Maryland,Baltimore,4700 block of Liberty Heights Ave,1,3,October 29,2019,39.299236,-76.609383,Baltimore
36,1536787,Maryland,Baltimore,4160 Pimlico Rd,1,3,October 28,2019,39.299236,-76.609383,Baltimore
37,1525628,Maryland,Baltimore,800 block of W Lexington St,1,3,October 12,2019,39.299236,-76.609383,Baltimore
38,1523204,Maryland,Baltimore,1600 block of W North Ave,1,3,October 9,2019,39.299236,-76.609383,Baltimore
39,1493429,Maryland,Baltimore,900 block of N Monroe St,0,4,August 31,2019,39.299236,-76.609383,Baltimore
40,1491495,Maryland,Baltimore,1600 block of E 29th St,1,3,August 30,2019,39.299236,-76.609383,Baltimore
41,1490466,Maryland,Baltimore,2500 block of E Monument St,1,3,August 29,2019,39.299236,-76.609383,Baltimore
42,1453350,Maryland,Baltimore,2800 block of Boarman Ave,1,3,July 20,2019,39.299236,-76.609383,Baltimore
43,1437094,Maryland,Baltimore,1200 block of N Luzerne Ave,0,4,July 1,2019,39.299236,-76.609383,Baltimore
44,1428595,Maryland,Baltimore,800 block of N Port St,1,4,June 22,2019,39.299236,-76.609383,Baltimore
45,1405317,Maryland,Baltimore,500 block of N Belnord Ave,0,4,May 25,2019,39.299236,-76.609383,Baltimore
46,1386085,Maryland,Baltimore,1900 block of Ramsay St,0,5,May 3,2019,39.299236,-76.609383,Baltimore
47,1385642,Maryland,Baltimore,2500 block of E Biddle St,0,4,May 3,2019,39.299236,-76.609383,Baltimore
48,1381979,Maryland,Baltimore,2544 Edmondson Ave,1,7,April 28,2019,39.299236,-76.609383,Baltimore
49,1368597,Maryland,Baltimore,2200 block of Ruskin Ave,1,3,April 11,2019,39.299236,-76.609383,Baltimore

In [33]:
Gun_map_2019=Gun_map_2019.drop(columns=["City"])
Gun_map_2020=Gun_map_2020.drop(columns=["City"])
Gun_map_2021=Gun_map_2021.drop(columns=["City"])
Gun_map_2019

,Incident ID,State,City Or County,Address,# Killed,# Injured,Date,Year,Latitude,Longitude
0,1582197,New York,Buffalo,50 block of Henrietta Ave,1,3,December 29,2019,42.880230,-78.878738
1,1418548,New York,Buffalo,2081 Niagara St,0,4,June 9,2019,42.880230,-78.878738
2,1581590,California,Modesto,1900 block of Vernon Ave,1,3,December 27,2019,37.661388,-120.994446
3,1581103,Texas,Houston,500 block of Smart St,2,7,December 27,2019,29.749907,-95.358421
4,1541774,Texas,Houston,5000 block of Northridge Dr,1,4,November 4,2019,29.749907,-95.358421
...,...,...,...,...,...,...,...,...,...,...
358,1303303,California,Palmdale,Ranch Center Dr and 40th St W,3,1,January 16,2019,34.579449,-118.109291
359,1295294,New Mexico,Roswell,1300 block of W College Blvd,0,4,January 6,2019,34.022003,-84.361549
360,1293054,California,Torrance,22501 Hawthorne Blvd,3,4,January 4,2019,33.840763,-118.345413
361,1292941,Arizona,Yuma,3800 block of E County 18½ St,1,3,January 3,2019,32.698437,-114.650398
362,1291779,Arkansas,Jonesboro,3516 Galaxy St,1,3,January 2,2019,35.835575,-90.705025

In [34]:
Gun_map_2019.to_csv("Resource/Gun_violence_2019.csv",index=False)
Gun_map_2020.to_csv("Resource/Gun_violence_2020.csv",index=False)
Gun_map_2021.to_csv("Resource/Gun_violence_2021.csv",index=False)