In [24]:
import pandas as pd
from splinter import Browser
from bs4 import BeautifulSoup as bs
import time
from webdriver_manager.chrome import ChromeDriverManager
import pandas as pd

In [2]:
file1 = "mass_shooting_2019.csv"
file2 = "mass_shooting_2020.csv"
file3 = "mass_shooting_2021.csv"

In [3]:
df_2019 = pd.read_csv(file1)
df_2020 = pd.read_csv(file2)
df_2021 = pd.read_csv(file3)

In [4]:
df_2019

,Incident ID,Incident Date,State,City Or County,Address,# Killed,# Injured,Operations
0,1582816,"December 29, 2019",Illinois,Danville,1803 block of Westview Ave,0,5,NaN
1,1582197,"December 29, 2019",New York,Buffalo,50 block of Henrietta Ave,1,3,NaN
2,1583444,"December 29, 2019",California,Ceres,800 block of Allacante Dr,0,5,NaN
3,1581590,"December 27, 2019",California,Modesto,1900 block of Vernon Ave,1,3,NaN
4,1581103,"December 27, 2019",Texas,Houston,500 block of Smart St,2,7,NaN
...,...,...,...,...,...,...,...,...
412,1293054,"January 4, 2019",California,Torrance,22501 Hawthorne Blvd,3,4,NaN
413,1292941,"January 3, 2019",Arizona,Yuma,3800 block of E County 18½ St,1,3,NaN
414,1291779,"January 2, 2019",Arkansas,Jonesboro,3516 Galaxy St,1,3,NaN
415,1289877,"January 1, 2019",South Carolina,Columbia,1709 Decker Blvd,0,5,NaN
416,1289618,"January 1, 2019",Florida,Tallahassee,2020 W Pensacola St,0,5,NaN

In [5]:
df_2020

,Incident ID,Incident Date,State,City Or County,Address,# Killed,# Injured,Operations
0,1891461,"December 31, 2020",Indiana,Indianapolis,8215 Center Run Road,1,3,NaN
1,1890946,"December 31, 2020",Oregon,Happy Valley,9200 block of SE Idleman Rd,0,4,NaN
2,1886974,"December 26, 2020",Illinois,Rockford,4007 E State St,3,3,NaN
3,1886913,"December 26, 2020",Florida,Tampa,N 20th St and E 7th Ave,2,2,NaN
4,1887059,"December 26, 2020",Massachusetts,Lynn,Washington St and Quincy Ter,1,5,NaN
...,...,...,...,...,...,...,...,...
606,1588308,"January 4, 2020",Florida,Ocala,800 block of NW 6th Ter,1,3,NaN
607,1586839,"January 2, 2020",New York,Brooklyn,6120 3rd Ave,0,4,NaN
608,1585746,"January 1, 2020",Ohio,Cleveland,1437 St Clair Ave NE,0,4,NaN
609,1585394,"January 1, 2020",West Virginia,Huntington,1113 4th Ave,0,7,NaN
610,1585894,"January 1, 2020",Missouri,Saint Louis,3000 block of S Jefferson Ave,3,2,NaN

In [6]:
df_2021

,Incident ID,Incident Date,State,City Or County,Address,# Killed,# Injured,Operations
0,2125953,"September 26, 2021",California,Oakland,1400 block of 8th Ave,0,4,NaN
1,2125790,"September 26, 2021",Illinois,Chicago,800 block of S Albany Ave,0,0,NaN
2,2125613,"September 25, 2021",New York,Utica,800 block of Mohawk St,0,4,NaN
3,2125227,"September 25, 2021",California,Riverside,6000 Block of Mariposa Ave,0,6,NaN
4,2125444,"September 25, 2021",Tennessee,Athens,Co Rd 60,4,0,NaN
...,...,...,...,...,...,...,...,...
518,1893744,"January 3, 2021",Florida,Miami,10525 NW 24th Ave,0,8,NaN
519,1892114,"January 1, 2021",Iowa,Sioux City,2637 S Walker St,1,4,NaN
520,1892034,"January 1, 2021",Arkansas,Fort Smith,3211 Towson Ave,0,7,NaN
521,1892704,"January 1, 2021",Texas,Amarillo,2650 Dumas Dr,1,3,NaN
522,1891720,"January 1, 2021",Illinois,Galesburg,1000 block of Monroe St,0,4,NaN

In [7]:
frames = [df_2019, df_2020, df_2021]

result = pd.concat(frames)

In [8]:
result

,Incident ID,Incident Date,State,City Or County,Address,# Killed,# Injured,Operations
0,1582816,"December 29, 2019",Illinois,Danville,1803 block of Westview Ave,0,5,NaN
1,1582197,"December 29, 2019",New York,Buffalo,50 block of Henrietta Ave,1,3,NaN
2,1583444,"December 29, 2019",California,Ceres,800 block of Allacante Dr,0,5,NaN
3,1581590,"December 27, 2019",California,Modesto,1900 block of Vernon Ave,1,3,NaN
4,1581103,"December 27, 2019",Texas,Houston,500 block of Smart St,2,7,NaN
...,...,...,...,...,...,...,...,...
518,1893744,"January 3, 2021",Florida,Miami,10525 NW 24th Ave,0,8,NaN
519,1892114,"January 1, 2021",Iowa,Sioux City,2637 S Walker St,1,4,NaN
520,1892034,"January 1, 2021",Arkansas,Fort Smith,3211 Towson Ave,0,7,NaN
521,1892704,"January 1, 2021",Texas,Amarillo,2650 Dumas Dr,1,3,NaN
522,1891720,"January 1, 2021",Illinois,Galesburg,1000 block of Monroe St,0,4,NaN

In [9]:
result["Full_Address"] = result['Address'] + ', ' + result['City Or County'] + ' ' + result['State']

In [10]:
result

,Incident ID,Incident Date,State,City Or County,Address,# Killed,# Injured,Operations,Full_Address
0,1582816,"December 29, 2019",Illinois,Danville,1803 block of Westview Ave,0,5,NaN,"1803 block of Westview Ave, Danville Illinois"
1,1582197,"December 29, 2019",New York,Buffalo,50 block of Henrietta Ave,1,3,NaN,"50 block of Henrietta Ave, Buffalo New York"
2,1583444,"December 29, 2019",California,Ceres,800 block of Allacante Dr,0,5,NaN,"800 block of Allacante Dr, Ceres California"
3,1581590,"December 27, 2019",California,Modesto,1900 block of Vernon Ave,1,3,NaN,"1900 block of Vernon Ave, Modesto California"
4,1581103,"December 27, 2019",Texas,Houston,500 block of Smart St,2,7,NaN,"500 block of Smart St, Houston Texas"
...,...,...,...,...,...,...,...,...,...
518,1893744,"January 3, 2021",Florida,Miami,10525 NW 24th Ave,0,8,NaN,"10525 NW 24th Ave, Miami Florida"
519,1892114,"January 1, 2021",Iowa,Sioux City,2637 S Walker St,1,4,NaN,"2637 S Walker St, Sioux City Iowa"
520,1892034,"January 1, 2021",Arkansas,Fort Smith,3211 Towson Ave,0,7,NaN,"3211 Towson Ave, Fort Smith Arkansas"
521,1892704,"January 1, 2021",Texas,Amarillo,2650 Dumas Dr,1,3,NaN,"2650 Dumas Dr, Amarillo Texas"
522,1891720,"January 1, 2021",Illinois,Galesburg,1000 block of Monroe St,0,4,NaN,"1000 block of Monroe St, Galesburg Illinois"

In [11]:
from geopy.extra.rate_limiter import RateLimiter
from geopy.geocoders import Nominatim

locator = Nominatim(user_agent="myGeocoder")

In [12]:
# 1 - conveneint function to delay between geocoding calls
#geocode = RateLimiter(locator.geocode, min_delay_seconds=1)
geocode = locator.geocode
# 2- - create location column
result['location'] = result['Full_Address'].apply(geocode)

# 3 - create longitude, laatitude and altitude from location column (returns tuple)
result['point'] = result['location'].apply(lambda loc: tuple(loc.point) if loc else None)

# 4 - split point column into latitude, longitude and altitude columns
#result[['latitude', 'longitude', 'altitude']] = pd.DataFrame(result['point'].tolist())

In [13]:
result

,Incident ID,Incident Date,State,City Or County,Address,# Killed,# Injured,Operations,Full_Address,location,point
0,1582816,"December 29, 2019",Illinois,Danville,1803 block of Westview Ave,0,5,NaN,"1803 block of Westview Ave, Danville Illinois",None,None
1,1582197,"December 29, 2019",New York,Buffalo,50 block of Henrietta Ave,1,3,NaN,"50 block of Henrietta Ave, Buffalo New York",None,None
2,1583444,"December 29, 2019",California,Ceres,800 block of Allacante Dr,0,5,NaN,"800 block of Allacante Dr, Ceres California",None,None
3,1581590,"December 27, 2019",California,Modesto,1900 block of Vernon Ave,1,3,NaN,"1900 block of Vernon Ave, Modesto California",None,None
4,1581103,"December 27, 2019",Texas,Houston,500 block of Smart St,2,7,NaN,"500 block of Smart St, Houston Texas",None,None
...,...,...,...,...,...,...,...,...,...,...,...
518,1893744,"January 3, 2021",Florida,Miami,10525 NW 24th Ave,0,8,NaN,"10525 NW 24th Ave, Miami Florida","(10525, Northwest 24th Avenue, West Little Riv...","(25.8712413, -80.2382308, 0.0)"
519,1892114,"January 1, 2021",Iowa,Sioux City,2637 S Walker St,1,4,NaN,"2637 S Walker St, Sioux City Iowa","(2637, South Walker Street, Sioux City, Woodbu...","(42.462977157894734, -96.33166884210527, 0.0)"
520,1892034,"January 1, 2021",Arkansas,Fort Smith,3211 Towson Ave,0,7,NaN,"3211 Towson Ave, Fort Smith Arkansas","(3211, Towson Avenue, Mill Creek, Fort Smith, ...","(35.353577265822786, -94.42203451898735, 0.0)"
521,1892704,"January 1, 2021",Texas,Amarillo,2650 Dumas Dr,1,3,NaN,"2650 Dumas Dr, Amarillo Texas","(2650, Dumas Drive, Amarillo, Potter County, T...","(35.24087693805399, -101.83087625516222, 0.0)"
522,1891720,"January 1, 2021",Illinois,Galesburg,1000 block of Monroe St,0,4,NaN,"1000 block of Monroe St, Galesburg Illinois",None,None

In [14]:
df_2019

,Incident ID,Incident Date,State,City Or County,Address,# Killed,# Injured,Operations
0,1582816,"December 29, 2019",Illinois,Danville,1803 block of Westview Ave,0,5,NaN
1,1582197,"December 29, 2019",New York,Buffalo,50 block of Henrietta Ave,1,3,NaN
2,1583444,"December 29, 2019",California,Ceres,800 block of Allacante Dr,0,5,NaN
3,1581590,"December 27, 2019",California,Modesto,1900 block of Vernon Ave,1,3,NaN
4,1581103,"December 27, 2019",Texas,Houston,500 block of Smart St,2,7,NaN
...,...,...,...,...,...,...,...,...
412,1293054,"January 4, 2019",California,Torrance,22501 Hawthorne Blvd,3,4,NaN
413,1292941,"January 3, 2019",Arizona,Yuma,3800 block of E County 18½ St,1,3,NaN
414,1291779,"January 2, 2019",Arkansas,Jonesboro,3516 Galaxy St,1,3,NaN
415,1289877,"January 1, 2019",South Carolina,Columbia,1709 Decker Blvd,0,5,NaN
416,1289618,"January 1, 2019",Florida,Tallahassee,2020 W Pensacola St,0,5,NaN

In [16]:
incident_numbers_2019 = df_2019["Incident ID"].tolist()

In [19]:
incident_numbers_2019

[1582816,
 1582197,
 1583444,
 1581590,
 1581103,
 1581476,
 1580308,
 1579889,
 1579970,
 1579856,
 1579266,
 1594317,
 1579220,
 1577577,
 1577688,
 1577518,
 1578711,
 1577046,
 1577438,
 1575175,
 1573754,
 1572275,
 1573471,
 1571348,
 1568230,
 1567932,
 1567231,
 1565216,
 1564524,
 1562043,
 1561966,
 1561813,
 1562685,
 1561734,
 1561398,
 1560645,
 1559257,
 1558067,
 1557006,
 1556633,
 1556984,
 1555879,
 1556002,
 1555135,
 1554807,
 1554446,
 1552068,
 1551531,
 1551162,
 1550546,
 1548689,
 1547021,
 1546102,
 1546038,
 1546155,
 1545955,
 1546508,
 1545027,
 1543835,
 1541774,
 1540863,
 1540841,
 1540280,
 1540240,
 1539572,
 1539557,
 1539347,
 1537992,
 1537044,
 1537672,
 1536787,
 1536706,
 1535629,
 1535478,
 1534704,
 1533166,
 1531326,
 1530965,
 1530407,
 1530276,
 1527528,
 1525999,
 1526952,
 1525062,
 1525476,
 1525408,
 1525628,
 1525265,
 1523606,
 1524264,
 1522979,
 1523204,
 1521226,
 1520425,
 1520499,
 1520330,
 1520547,
 1519090,
 1518859,
 1517804,
 1515312,
 1515242,
 1515128,
 1517360,
 1515327,
 1511999,
 1510411,
 1509721,
 1509411,
 1508804,
 1509510,
 1512486,
 1508859,
 1507939,
 1507156,
 1507092,
 1505354,
 1504030,
 1504012,
 1504387,
 1503207,
 1503192,
 1501350,
 1499460,
 1500098,
 1499300,
 1497702,
 1497180,
 1494697,
 1495141,
 1495192,
 1494113,
 1494669,
 1494548,
 1493374,
 1492778,
 1492377,
 1492441,
 1492264,
 1493429,
 1492297,
 1493038,
 1491495,
 1492087,
 1490466,
 1487729,
 1487573,
 1487356,
 1487224,
 1486232,
 1489373,
 1486675,
 1485340,
 1485548,
 1484335,
 1482199,
 1481989,
 1480326,
 1479894,
 1478869,
 1479395,
 1478480,
 1475924,
 1475361,
 1476271,
 1475208,
 1472641,
 1469344,
 1527721,
 1468190,
 1468799,
 1468091,
 1467828,
 1466705,
 1467157,
 1462317,
 1460630,
 1460448,
 1461352,
 1459941,
 1460726,
 1459389,
 1459718,
 1459201,
 1457165,
 1453327,
 1453884,
 1453350,
 1452654,
 1452617,
 1450767,
 1450124,
 1449602,
 1448578,
 1447456,
 1446611,
 1447057,
 1445066,
 1441967,
 1441565,
 1441613,
 1441396,
 1441296,
 1441317,
 1441427,
 1441721,
 1440510,
 1440879,
 1439593,
 1440257,
 1440765,
 1439737,
 1438971,
 1439765,
 1439042,
 1438602,
 1437094,
 1435804,
 1436545,
 1436254,
 1435578,
 1435041,
 1435297,
 1434931,
 1435028,
 1434882,
 1434602,
 1434971,
 1434893,
 1435217,
 1432989,
 1432930,
 1433857,
 1429475,
 1429810,
 1429047,
 1429480,
 1429338,
 1429399,
 1429022,
 1428595,
 1428788,
 1427483,
 1428047,
 1428229,
 1426537,
 1425193,
 1425161,
 1424957,
 1423697,
 1423330,
 1423435,
 1422981,
 1420933,
 1419305,
 1420432,
 1418533,
 1418548,
 1418457,
 1418180,
 1417570,
 1417716,
 1416374,
 1415399,
 1412419,
 1411598,
 1411408,
 1412243,
 1411963,
 1412430,
 1410442,
 1411661,
 1410329,
 1408289,
 1409255,
 1407941,
 1406330,
 1407189,
 1405445,
 1405749,
 1406070,
 1404417,
 1404580,
 1405196,
 1405317,
 1405221,
 1400095,
 1400146,
 1400561,
 1399820,
 1399017,
 1398553,
 1398538,
 1398593,
 1398584,
 1400934,
 1399346,
 1398876,
 1397521,
 1396491,
 1395560,
 1393960,
 1394330,
 1392923,
 1391971,
 1392313,
 1390764,
 1389220,
 1386962,
 1387170,
 1386510,
 1386929,
 1387245,
 1386575,
 1386481,
 1386085,
 1385642,
 1384553,
 1383752,
 1381857,
 1382099,
 1381979,
 1382711,
 1381771,
 1381273,
 1381734,
 1377519,
 1376873,
 1376883,
 1375235,
 1373557,
 1370795,
 1371024,
 1371065,
 1374920,
 1370269,
 1368597,
 1369109,
 1369148,
 1367011,
 1365052,
 1365077,
 1365173,
 1365100,
 1364443,
 1364540,
 1363737,
 1362715,
 1362364,
 1362182,
 1360333,
 1359599,
 1359455,
 1357591,
 1355275,
 1353714,
 1354049,
 1350494,
 1348844,
 1349256,
 1348793,
 1347974,
 1348291,
 1347894,
 1344488,
 1343330,
 1343274,
 1338860,
 1338765,
 1338790,
 1337498,
 1333480,
 1331974,
 1332507,
 1332429,
 1332181,
 1329144,
 1328792,
 1329075,
 1328562,
 1327321,
 1324279,
 1323448,
 1321021,
 1321093,
 1319333,
 1319325,
 1318391,
 1320286,
 1318187,
 1314289,
 1314253,
 1312391,
 1312284,
 1312463,
 1313291,
 1310775,
 1310397,
 1309114,
 1306920,
 1305563,
 1305679,
 1305516,
 1305538,
 1305294,
 1303486,
 1302060,
 1303303,
 1301778,
 1299680,
 1295294,
 1292684,
 1293054,
 1292941,
 1291779,
 1289877,
 1289618]

In [ ]:
def scrape_info_3(incident_list):

    executable_path = {'executable_path': ChromeDriverManager().install()}
    browser = Browser('chrome', **executable_path, headless=False)


    url = "https://www.gunviolencearchive.org/incident/"
    

    time.sleep(1)
    

#     xpath = '//*[@id="product-section"]/div[2]/div[1]/div/a/h3'
#     xpath2 = '//*[@id="product-section"]/div[2]/div[2]/div/a/h3'
#     xpath3 = '//*[@id="product-section"]/div[2]/div[3]/div/a/h3'
#     xpath4 = '//*[@id="product-section"]/div[2]/div[4]/div/a/h3'
    
    
#     info_dict = []
#     xpath_list = [xpath, xpath2, xpath3, xpath4]
    
    
    
    for x in incident_list:
        #results = browser.find_by_xpath(x)
        
        browser.visit(url + x)
        
#         click = results[0]
#         click.click()

        html = browser.html
        soup = bs(html, "html.parser")
        
        
        spans = soup.findAll('span')

#         hemi_title = soup.find('h2', class_='title').text
#         full_image = soup.find('img', class_='wide-image')['src']
#         full_image_url = url + full_image
        
#         data = {
#             "title": hemi_title,
#             "img_url": full_image_url
#         }
#         info_dict.append(data)
#         browser.back()

    
    browser.quit()
    
    return info_dict

In [26]:
executable_path = {'executable_path': ChromeDriverManager().install()}
browser = Browser('chrome', **executable_path, headless=False)


url = "https://www.gunviolencearchive.org/incident/"


#time.sleep(1)
    
#for x in incident_numbers_2019:

browser.visit(url + "1582816")

html = browser.html
soup = bs(html, "html.parser")

spans = soup.findAll('span')

for span in spans:
    print(span.text)
    
browser.quit()

====== WebDriver manager ======
Current google-chrome version is 93.0.4577
Get LATEST driver version for 93.0.4577
Driver [C:\Users\Trevor\.wdm\drivers\chromedriver\win32\93.0.4577.63\chromedriver.exe] found in cache

Please turn JavaScript on and reload the page.







Checking your browser before accessing gunviolencearchive.org.

Please enable Cookies and reload the page.

This process is automatic. Your browser will redirect to your requested content shortly.
Please allow up to 5 seconds…
Redirecting…








error code: 1020




Checking your browser before accessing
error code: 1020